services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=web
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user.com
    volumes:
      - /d/web/建立表格.sql:/docker-entrypoint-initdb.d/建立表格.sql
    ports:
      - "3306:3306"
