-- 建立 User 表
CREATE TABLE User (
  UserID INT(10) AUTO_INCREMENT PRIMARY KEY,    -- 使用者ID，自動編號主鍵
  Phone CHAR(10) NOT NULL UNIQUE,               -- 手機號碼，10碼，且唯一
  UserName VARCHAR(100),
  Email VARCHAR(200),
  Password VARCHAR(255),
  CoverImage VARCHAR(500),
  Biography TEXT
);

-- 建立 Post 表
CREATE TABLE Post (
  PostID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  Content TEXT NOT NULL,
  Image VARCHAR(500) DEFAULT NULL,
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_user
    FOREIGN KEY (UserID) REFERENCES User(UserID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

-- 建立 Comment 表
CREATE TABLE Comment (
  CommentID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  PostID INT NOT NULL,
  Content TEXT NOT NULL,
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_comment_user
    FOREIGN KEY (UserID) REFERENCES User(UserID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_comment_post
    FOREIGN KEY (PostID) REFERENCES Post(PostID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);